### ISSUE TITLE
Latest libavcodec still depends on R_2020 symbols with --enable-videotoolbox

### ISSUE THREAD

**Issue by Kagami** [Kagami/boram#12]
https://github.com/FFmpeg/FFmpeg/commit/dcd3418a35aab7ef283b68ed9997ce4ac204094e
https://trac.ffmpeg.org/ticket/6081
https://developer.apple.com/reference/corevideo/kcvimagebuffercolorprimaries_itu_r_2020

**Comment by Kagami** [comment]
Should be fixed in https://github.com/FFmpeg/FFmpeg/commit/70ebc05bce51215cd0857194d6cabf1e4d1440fb
@romaincointepas, mind testing [ffmpeg-cifix-vboxfix2.zip](https://github.com/Kagami/boram/files/811323/ffmpeg-cifix-vboxfix2.zip)?

**Comment by romaincointepas** [comment]
Works!

**Comment by Kagami** [comment]
Nice.
videotoolbox is the only available hwdec API in mpv btw, so we surely want it enabled.

**Comment by romaincointepas** [comment]
On Mac yes, on Windows there are plenty and as far as I've read, the decoding bugs usually happen there :/
