### ISSUE TITLE
Enable vp9 highbitdepth

### ISSUE THREAD

**Issue by hmsintrepide** [Kagami/boram#17]
Can you enable by default vp9 highbitdepth, for using profile 2 (10-bit) ?

You create a great GUI, better than handbrake and staxrip

**Comment by hmsintrepide** [comment]
Like this https://github.com/hmsintrepide/boram/commit/ac25fbde225a0d259021e44ec47d3df9dfaa5eeb

**Comment by Kagami** [comment]
I published builds with enabled high bitdepth. I don't think it's necessary to create GUI option for that (there isn't much free space anyway), just fix `pix_fmt` option in raw args string.

E.g. for 10-bit encode you need to replace `yuv420p` with `yuv420p10`.
