### ISSUE TITLE
FIXME: missed GL function glBufferSubData

### ISSUE THREAD

**Issue by sirx** [Kagami/boram#22]
Hello!

I installed the latest version using your link for relases and have mpv etc. all installed, but I get the following error:

FIXME: missed GL function glBufferSubData
failed to initialize mpv GL context

any idea how to fix it?

Thanks!

**Comment by Kagami** [comment]
Latest mpv requires some fixes. I've already pushed them to master, now need to make a new release.

**Comment by sirx** [comment]
Thanks for answering! 

Can you maybe explain how to compile it? I'd really love to use this tool.

**Comment by Kagami** [comment]
Should be fixed in 0.3.6.

**Comment by sirx** [comment]
Thank you very much! Works perfectly!
