### ISSUE TITLE
Fail to start on ubunt, ld

### ISSUE THREAD

**Issue by osv** [Kagami/boram#25]
Common, why you use own checklib implementation and why not ldconfig? I install libmpvt but still cannot start this app.

Version: `boram-v0.3.7-linux-x64`

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

$ ldconfig -p | grep libmpv
	libmpv.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libmpv.so.1
```

**Comment by Kagami** [comment]
>why not ldconfig?

It's a bit more robust. E.g. if you want to use `LD_LIBRARY_PATH` env variable instead of global install...

>but still cannot start this app

Does

```
$ /path/to/checklib libmpv.so.1 && echo OK
```

print anything?

**Comment by osv** [comment]
Hm, probably unpack problem, because I did `chmod +x ./boram` before.. And now I changed:
```
chmod +x ./resources/app/checklib
```
and this solved my start problem

**Comment by Kagami** [comment]
Hm, exactly same problem was mentioned here https://github.com/Kagami/boram/issues/18#issuecomment-341291050
What command did you use for unpacking? It works just fine with `7z x boram-v0.3.7-linux-x64.7z` for me.

**Comment by osv** [comment]
I used midnight commander for extracting. In any case all work fine now, video encoded
