### ISSUE TITLE
Failed to build on Windows because of unescaped character

### ISSUE THREAD

**Issue by OrcaXS** [Kagami/boram#27]
On Windows, `npm run app`  would return
```
ModuleParseError: Module parse failed: C:\projects\boram\src\index\renderer.js Unexpected character '@' (18:0)
You may need an appropriate loader to handle this file type.
```
Because `return new RegExp("^" + path.join(__dirname, ...parts) + "$");` returned something like `^c:\projects\boram\src\.+\.js$` which isn't a correct RegEx, so webpack (babel-loader) can't resolve correct path of .js and font-awesome .css files.

A simple block like
```javascript
{
  test: /\.js$/,
  loader: "babel",
  include: path.join(__dirname, "src"),
},
```
could solve the problem, though it'd make the `intree` function unused.

**Comment by Kagami** [comment]
Thanks for the report. Please try now.
