### ISSUE TITLE
How can I get alpha channel?

### ISSUE THREAD

**Issue by Yomolotakowapo** [Kagami/boram#28]
Hello there!

Thank you so much for this incredible program! Really love it!. My problem is about getting alpha channel. I get always black screen.... Please I need your help! 

Thank you very much!

**Comment by Kagami** [comment]
Hi. I'm not sure I understand. Do you want to create webm with alpha channel? Try to change `yuv420p` to `yuva420p` in raw args field then.

**Comment by Yomolotakowapo** [comment]
Kagami, I love you. Really I love this program and your help! Amazing. That´s right I have MY ALPHA CHANNEL !!!! THANK YOU THANK YOU THANK YOU!!!!

**Comment by Kagami** [comment]
I'm glad it works :)
