### ISSUE TITLE
mp4 is not encoded to webm

### ISSUE THREAD

**Issue by Ygarr** [Kagami/boram#3]
original mp4 data:
VideoStream: H264 - MPEG-4 AVC (part 10 avc1)
624x354
frame rate: 23.976000
Decoded format: Planar 4:2:0 YUV

Audiotream:
MPEG AAC Audio (mp4a)
Stereo
Sample rate: 48 000 Hz

original:  Converted with Kdenlive: Other Data in attach.
![2016-12-14-110727_497x509_scrot](https://cloud.githubusercontent.com/assets/14309871/21175974/85404e0e-c1ed-11e6-9139-b7f838e2bf5b.png)

Preview works(one first time).
.Error: Cannot copy - in attach
![2016-12-14-111207_1672x238_scrot](https://cloud.githubusercontent.com/assets/14309871/21176153/389a8da2-c1ee-11e6-8993-1d9a7b898370.png)
![2016-12-14-111217_982x143_scrot](https://cloud.githubusercontent.com/assets/14309871/21176152/389a4996-c1ee-11e6-9f7f-14940ef8be33.png)

**Comment by Ygarr** [comment]
OS: Debian Sid

**Comment by Kagami** [comment]
Hi. Could you please upload sample?
`ffmpeg -i vid.mp4 -c copy -t 5 sample.mp4` to make short one.

**Comment by Ygarr** [comment]
dats it
[sample.zip](https://github.com/Kagami/boram/files/653581/sample.zip)

**Comment by Kagami** [comment]
libvpx [doesn't accept](https://chromium.googlesource.com/webm/libvpx/+/v1.6.0/vp9/vp9_cx_iface.c#162) such huge timebase denumerator. Clearly not a boram's issue.

You can change timebase of file without reencoding with something like:
`ffmpeg -i sample.mp4 -c copy -video_track_timescale 1000 fixed-sample.mp4`
That works for me.
