### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ritalinn** [Kagami/boram#32]
I am an open source fan. I volunteer a logo. I made one for you. I'm waiting for your thoughts.

![boram](https://user-images.githubusercontent.com/41344739/42967461-fd6b7454-8ba8-11e8-865d-d75c37f175a6.jpg)

**Comment by Kagami** [comment]
Thanks, but boram [already has a logo](https://github.com/Kagami/boram/blob/master/src/index/icon-big.png).
