### ISSUE TITLE
Cannot convert/download youtube link

### ISSUE THREAD

**Issue by Ygarr** [Kagami/boram#4]
Seems not strictly Boram issue but cannot download this link:
https://www.youtube.com/watch?v=pOwav6hvWbU

But got strange unresolvable youtube-dl or python 
![2017-01-12-023015_1283x976_scrot](https://cloud.githubusercontent.com/assets/14309871/21872081/16460d48-d86f-11e6-8551-383b25f5633d.png)
error. May be alternative download engine?:

youtube-dl exited with code 1 (WARNING: video doesn't have subtitles ERROR: Signature extraction failed: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature video_id, player_url, s File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function cache_res = res(test_string) File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 984, in <lambda> return lambda s: initial_function([s]) File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 254, in resf res, abort = self.interpret_statement(stmt, local_vars) File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement v = self.interpret_expression(expr, local_vars, allow_recursion) File "/usr/lib/python3/dist-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression return obj[member](argvals) KeyError: 'qC' (caused by KeyError('qC',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.)

**Comment by Kagami** [comment]
Seems like your system version of youtube-dl is too old. Try `youtube-dl -U`.

**Comment by Ygarr** [comment]
"It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update."

But it is last for package manager.

**Comment by Kagami** [comment]
Well, you need to update it somehow. You can just uninstall package and boram will use the bundled one, or download [binary](https://yt-dl.org/latest/youtube-dl) and put it in e.g. `/usr/local/bin`.

Post `youtube-dl --version` just in case. Should be `2017.01.10`, otherwise youtube links will return that error.

**Comment by Ygarr** [comment]
2017-01-12 12:19:04 ⌚  sidbox in ~
○ → youtube-dl --version
2016.12.01

**Comment by Ygarr** [comment]
Without installed youtube-dl all works fine
