### ISSUE TITLE
AV1 compression no work

### ISSUE THREAD

**Issue by IlluminatiWave** [Kagami/boram#41]
The promised superior codec compression didn't work.

My video originally lasted 20 minutes, but I decided to convert the last 3 minutes to try

Leaving aside that it takes 3 days to convert it. It came to weigh a little less than the video with a duration of 20 minutes, only a piece of 3.

Also the video reproduces with frightful slowness

My spec

Core i5 4200U
12 GB RAM DDR3 SoDIMM
Gtx 840M (2 GB VRAM)

Energy profile "Maximum performance"
Real-time execution
Nothing open

-----Video Specs------
Input
File size = 2965 MB
Duration = 21:34
Bitrate = 19209
Container = QuickTime / MOV

Video Codec = h264
Resolution = 1296x732
Frame Rate = 60fps
Pixel format = yuv420p

Audio Codec = aac
Channels = 2(Stereo)

Output
File size = 2062 MB
Duration = 3:09
Bitrate = 91555Kbps (wtf)
Container = Matroska / WebM

Video Codec = av1
Resolution = 1296x732
Frame Rate = 60fps
Pixel format = yuv420p

Audio Codec = Vorbis
Channels = 2(Stereo)

**Comment by Kagami** [comment]
Hi. What do you mean by "doesn't work"? What error do you get?

**Comment by Kagami** [comment]
As far as I can understand, libaom works too slow for you. There is no much we can do here, though right now I'm updating it to the latest git version with better build flags, so it might help a bit. Also we have similar issue regarding AV1 in #42, so closing this one.

Regarding slow playback - you may try new dav1d decoder. Though it seems to be not included in mpv builds [here](https://mpv.srsfckn.biz), so you may search other builds / build by yourself with [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite). Also I'm planning to enable dav1d in new boram builds too.

Regarding output size - that depends on the bitrate/qp you set. If your 3-minute cut has same bitrate as 20-minute, size should be the same. New AV1 codec should improve compression for the *same bitrate*, but it will use the bitrate you specified.

**Comment by Kagami** [comment]
Please try 0.5.4 release.
