### ISSUE TITLE
Add build/compile scripts

### ISSUE THREAD

**Issue by EwoutH** [Kagami/boram#47]
It would be nice to be able to compile Boram ourselfs. Could you upload your build/compile scripts to GitHub?

Also some info in the Readme would be nice.

**Comment by Kagami** [comment]
Duplicate of #19.

Most builds commands are in [package.json](https://github.com/Kagami/boram/blob/master/package.json).
To build ffmpeg and its deps on macOS I'm using [make-mac64-deps.sh](https://github.com/Kagami/boram/blob/master/scripts/make-mac64-deps.sh).
On Windows I'm using [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite) for that with simple config and few fixes.
