### ISSUE TITLE
Not able to download youtube video

### ISSUE THREAD

**Issue by gagarine** [Kagami/boram#55]
I tried with this URL: https://www.youtube.com/watch?v=6Py_P1_cHUE

Got this error (copy past is hard, text disappear):
![Screenshot 2019-05-30 at 20 45 31](https://user-images.githubusercontent.com/164074/58656108-f3412800-831b-11e9-8b72-27e1d6286cd0.png)

**Comment by Kagami** [comment]
Thank you for the report. Should be fixed in 0.5.5.
