### ISSUE TITLE
Suggestion: Frame Trim Tool

### ISSUE THREAD

**Issue by Gorthezar** [Kagami/boram#56]
Just wanted to say out of all the programs I've used this one is the most stable and works the best consistently.
 One of the other programs I've tried has a frame by frame trim tool but it is very laggy is this something that could be added to Boram potentially? Image below for potential reference.

![image](https://user-images.githubusercontent.com/20695078/61977853-6bd30680-afa4-11e9-8690-66a79c6ce81e.png)

**Comment by Kagami** [comment]
Try to use "," and "." hotkeys (comma and dot) to step one frame backward/forward.

**Comment by Gorthezar** [comment]
Legit didn't know this was a thing. Thanks for the help and for making and maintaining this.
