### ISSUE TITLE
Use ffmpeg from system PATH

### ISSUE THREAD

**Issue by sturmen** [Kagami/boram#57]
I use [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite) to keep an updated ffmpeg build on my system with the latest libvpx & libaom (among others), accessible in my PATH. Would it be possible for Boram to use the newer binary when available?

**Comment by Kagami** [comment]
Yes, you need to export environment variable:

```
BORAM_FFMPEG=C:/dir/ffmpeg.exe
```

See e.g. [here](https://superuser.com/a/989665) how to set env variable in Windows.
