### ISSUE TITLE
Debian GNU/Linux: cannot load plugin, additional packages needed

### ISSUE THREAD

**Issue by rlafuente** [Kagami/boram#58]
This should work to get Boram running on Debian:

    sudo apt install libgconf-2-4 libmpv1

I do get a `Couldn't load plugin` message after downloading, in the preview window, and here I'm lost about what to do... what needs to be installed to display it?

**Comment by Kagami** [comment]
What ffmpeg version do you have? You may need to apply fix for ffmpeg 3, see: https://github.com/Kagami/boram#linux
