### ISSUE TITLE
mpv playback performance, hwdec

### ISSUE THREAD

**Issue by Kagami** [Kagami/boram#9]
Right now CPU usage is rather high. Need to try to activate hwdec (at least on some platforms or add UI control) and check whether it's possible to improve performance in some way.

**Comment by Kagami** [comment]
Might be useful: https://www.chromium.org/nativeclient/how-tos/3d-tips-and-best-practices

**Comment by Kagami** [comment]
I was thinking over this a bit. I'm not sure hwdec in internal player is much useful for boram usage per se. After all, you don't watch videos for hours, you only need to quickly find start/stop points and click to encode. In other words it's not worth the effort.

Though it makes sense to move mpv module into separate repo, making it usable for other electron apps which might want to implement some sort of video playback. And hwdec feature would fit much better.

@romaincointepas any thoughts?

**Comment by romaincointepas** [comment]
Yep definitely

**Comment by Kagami** [comment]
Moved to https://github.com/Kagami/mpv.js/issues/5
